### ISSUE TITLE
Get Trigger to ignore values out of range

### ISSUE THREAD

**Issue by aufdenkampe** [EnviroDIY/Trigger#5]
Right now I'm getting values of `0` from all of the Yosemitech variables before the sensor has fully warmed up. Also, sometimes numbers are coming out of a sensor that are unreasonably high.

@bschulz1701, can you add some min/max arguments to specify a valid range over which the trigger function evaluates. For conductivity, for example, I might give a range of 10-5000, so that a zero value doesn't trip it.

Many Thanks!

**Comment by bschulz1701** [comment]
I can do that, but it seems like a more appropriate way to go about it would be to specify in the Yosemitech library that if you get a value of 0, you should return -9999, and then tell the trigger code to ignore values of -9999, since there is functionality in that library which should cause it to only return a valid value of -9999

**Comment by aufdenkampe** [comment]
That seems reasonable. My -9999 isn't working at the moment, but I should make that happen.

In the meanwhile, any chance you could add to the Trigger library the functionality to ignore -9999 values? Thanks!

**Comment by bschulz1701** [comment]
Sure, that should be pretty simple

**Comment by bschulz1701** [comment]
Just pushed a fix which should work

**Comment by aufdenkampe** [comment]
Thanks! Let me check it out!

**Comment by aufdenkampe** [comment]
BTW, we just got -9999 values working for Yosemitech!

**Comment by aufdenkampe** [comment]
Could you also add an ignore values = `0`?
There are reasons why we don't want to set values of zero to -9999, but we don't want those to set the trigger either.

**Comment by bschulz1701** [comment]
Cool! And sure, just pushed the fix. 

I added that for now, but we should maybe think about that going forward, because I could see instances where 0 would be a valid result to trigger on, but no need to worry about true generality right now

**Comment by aufdenkampe** [comment]
These commits by @bschulz1701 close this issue.
https://github.com/EnviroDIY/Trigger/commit/ee8ed9d46040b8d6efbfa289516b3c4aa6474506
https://github.com/EnviroDIY/Trigger/commit/727e4e8a9236aadc2911fd31ed382b526604bb81

However, as @bschulz1701 points out, it is possible that `0` could be a valid value to trigger from. Perhaps we could add an optional argument to the constructor for the user to list all out-of-range values, rather than having those values hard-wired into the code.
